application: brainstorm-v2
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /css
  static_dir: css

- url: /img
  static_dir: img
  expiration: "1d"

- url: /.*
  script: main.py

inbound_services:
- channel_presence
